# Generated by Django 2.2 on 2019-12-16 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('original_lan', models.TextField(blank=True)),
                ('spoken_lan', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True)),
                ('production_companies', models.TextField(blank=True)),
                ('vote_average', models.IntegerField(blank=True)),
                ('vote_count', models.IntegerField(blank=True)),
            ],
        ),
    ]
