# Generated by Django 2.2 on 2019-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('original_lan', models.TextField(blank=True)),
                ('spoken_lan', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
