# Generated by Django 3.0 on 2019-12-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('overview', models.TextField()),
                ('original_lan', models.TextField()),
                ('spoken_lan', models.TextField()),
                ('genres', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
    ]
