# Generated by Django 2.2 on 2019-12-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='history_films',
            new_name='film_ratings',
        ),
    ]
