# Generated by Django 3.0 on 2019-12-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
